### ISSUE TITLE
Extension disables tab key

### ISSUE THREAD

**Issue by jjrsylvestre** [oscarlevin/pretext-tools#10]
With this extension enabled, pressing the tab key in a document causes the "Activating Extensions..." message to appear in the status bar, but nothing else. Normally tab key inserts/increases indentation, but with this extension enabled the tab key does nothing in terms of editing the document.

I've tried using both v0.6.0 and v0.6.1 of the extensions, same effect.

I'm using the OSS build of VS Code on Archlinux.
Code 1.70.2
Electron 18.3.9

**Comment by oscarlevin** [comment]
Strange.  I don't see this behavior, nor do I see what could be causing it.  I've tried both the marketplace version on windows and the oss build in cocalc.

So two thoughts: 
* Does the extension every finish activating?  It should activate as soon as you open a `.ptx` file.  You could also try the `PreTeXt-tools: refresh targets list` which would activate the extension.  
* Could there be another extension of setting you have that is conflicting somehow?  In VS Code settings, search on "tab" and see if anything looks fishy.

**Comment by oscarlevin** [comment]
Is this still an issue in the new releases?  I've done some refactoring, so I hope the problem has gone away.

**Comment by jjrsylvestre** [comment]
Yes, it is still an issue. I've had a chance to investigate a bit further: the issue only arises when the following are both true:

- the pretext-tools extension is enabled
- the setting `"emmet.triggerExpansionOnTab": true` is present in `settings.json`

I've tested with both the OSS build of Code and also the linux-x64 binary of Visual Studio Code provided by Microsoft. Same result in both.
