### ISSUE TITLE
Pretext is not running my project currently -- make vscode extension find workspace based on current file

### ISSUE THREAD

**Issue by Mike-git02** [oscarlevin/pretext-tools#102]
Here is screenshot of the output
![Screenshot from 2024-12-24 10-47-17](https://github.com/user-attachments/assets/0f82f3da-2b6f-4a03-8dcf-48b02b2fe348)

**Comment by oscarlevin** [comment]
Does the main.ptx file exist in that folder?

**Comment by Mike-git02** [comment]
Yes it has the main.ptx

**Comment by oscarlevin** [comment]
I think I know what is going on here: you are not running the pretext command from a "workspace" that has a project.ptx folder in it.  Try going to file -> Open Folder, and then select your pretext project (perhaps called "new-pretext-project".

You could also try changing to that directory (`cd new-pretext-project`) and then running the command `pretext build` from there.

This is a bug that I need to fix, so in a day or two this won't be needed.
