### ISSUE TITLE
Schema Validation

### ISSUE THREAD

**Issue by siefkenj** [oscarlevin/pretext-tools#11]
Schema validation and in-context suggestions would be great!

Here are some projects that might help:
 - https://github.com/raffazizzi/vscode-sxml
 - https://github.com/mangalam-research/salve
 - https://github.com/SAP/xml-tools

**Comment by oscarlevin** [comment]
Absolutely.  I'm currently collaborating with the maintainer of the vscode-sxml extension to add pretext support there.  Unclear how this will work for in-context suggestions compared to snippets, but at least the validation will work.

**Comment by siefkenj** [comment]
That's great :-). I am starting to play around with an LSP. I was thinking of forking vscode-sxml

**Comment by angelozerr** [comment]
Please note that vscode-xml provide this feature and more than only XML completion / validation based on XSD/DTD or RelaxNG (rng, rnc) schema, indeed it provides quickfix and another features like formatting, folding, rename tag, autoclose

See https://github.com/redhat-developer/vscode-xml/blob/main/docs/Features/XMLFeatures.md#xml-features

**Comment by oscarlevin** [comment]
As of 0.7, we now have schema validation provided by [vscode-xml](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-xml).  This works by default for any pretext file inside the `source` directory of your project.

**Comment by siefkenj** [comment]
I don't think this issue should be closed yet, given what we discussed yesterday about fragments not being checked correctly.

**Comment by angelozerr** [comment]
What do you mean with fragments? Perhaps xinclude?

Please create an issue in vscode-xml

**Comment by oscarlevin** [comment]
I will open an issue in vscode-xml as you suggest.  Yes, it's the behavior of the validation on xincluded files.

I think I'll open a second issue here rather than reopen this one.
