### ISSUE TITLE
PreText snippets should appear only for pretext language

### ISSUE THREAD

**Issue by angelozerr** [oscarlevin/pretext-tools#18]
When PretText extension is installed, the pretext snippets appears for any XML file which is very annoying if you open an XML file which have no reference with Pretext.

As you have defined a `pretext` language, I suggest that you use this language in https://github.com/oscarlevin/pretext-tools/blob/73104d8704b4e6f144cc8db2d985896a0e18f11f/package.json#L63 and not `xml` language

**Comment by oscarlevin** [comment]
Thanks for the push to look into why this wasn't working with setting the language to pretext.  I figured it out, and this should be fixed in the just released 0.7 version.

And thanks again @angelozerr for your support on the vscode-xml schema integration.
