### ISSUE TITLE
Get validation to work on xincluded files

### ISSUE THREAD

**Issue by oscarlevin** [oscarlevin/pretext-tools#21]
Reported the issue "upstream" at https://github.com/redhat-developer/vscode-xml/issues/845.  For now I will wait to see if there is a fix that can be made there.  Otherwise I can explore other options.

**Comment by angelozerr** [comment]
The issue should be fixed. Is vscode-xml supports correctly xi:include now? Please test it with vscode-xml prerelease.

**Comment by oscarlevin** [comment]
Yes, this is working perfectly now!
