### ISSUE TITLE
ignore non-alphanumeric characters in xml:id generation

### ISSUE THREAD

**Issue by StevenClontz** [oscarlevin/pretext-tools#23]
When I write the title `Lions, Tigers, and Bears (Oh My!)`, PreTeXt tools is suggesting the xml:id `subsec-lions,-tigers,-and-bears (Oh-my`

**Comment by angelozerr** [comment]
Could you give us a sample of ptx please with your issue. I'm not sure that it is managed by pretext tools. I think it is a vscode himself which mange those tokens by default when completion is opened.

I wonder if you open completion on the `<xref ref="|"` and you expect to see all @xml:id, is not that? if it that, vscode-xml starts supporting that, see https://github.com/oscarlevin/pretext-tools/issues/12#issuecomment-1368211470

**Comment by oscarlevin** [comment]
I think this is because I was trying to do something clever with snippets, that suggests a good name for the xml:id after a user types a `<title>` element.  I need to look into better regex to do the replacement.

**Comment by oscarlevin** [comment]
I've updated the regex to do the right thing, so this should be working on the next release
