### ISSUE TITLE
VSIX not compatible with CoCalc's VS Code

### ISSUE THREAD

**Issue by StevenClontz** [oscarlevin/pretext-tools#25]
This may be on CoCalc's end, but I'm getting `Unable to install extension 'oscarlevin.pretext-tools' as it is not compatible with VS Code '1.72.1'.` when trying to install on CoCalc.

**Comment by oscarlevin** [comment]
Looks like CoCalc now uses 1.78.x as it's VS Code version.  That's well within the current requirements.
