### ISSUE TITLE
Default snippet for 'c'

### ISSUE THREAD

**Issue by sean-fitzpatrick** [oscarlevin/pretext-tools#29]
I just noticed that if I type `c` and hit Tab, it autocompletes to the `CDATA` wrapper.
Since this is rarely needed any more, but `<c>...</c>` is used quite frequently, is there a way to change things so that `c+Tab` produces code formatting as the default?

**Comment by angelozerr** [comment]
@oscarlevin do you support cdata completion snippet? IF no I think it is a vscode xml

**Comment by oscarlevin** [comment]
I am pretty sure that I have a cdata snippet enabled, so I will look into seeing if there is anything that can be done about the order.  This is yet another argument for removing snippets and using only completions, so we can use vscode-xml's schema aware completion suggestions.

**Comment by sean-fitzpatrick** [comment]
I'm still trying to unlearn habits from 3 or 4 years of using Atom. Hitting either c or m and then tab is pretty ingrained muscle memory at this point!

**Comment by angelozerr** [comment]
>  we can use vscode-xml's schema aware completion suggestions.

I think it us the right direction to avoid polluating completion whith snippets which are not allowed.

But please keep in mind you will loose your advanced snippet which generate some non required attributes.

If you want to keep it it will require some work on vscode-xml.  See 
https://github.com/oscarlevin/pretext-tools/issues/3#issuecomment-1406481716

**Comment by oscarlevin** [comment]
This is now fixed with our new snippets as completion feature.
