### ISSUE TITLE
Schema validation - ignore certain warnings?

### ISSUE THREAD

**Issue by jmhammond** [oscarlevin/pretext-tools#42]
Hello! 

I just started using your extension to update my book, and I'm seeing a lot of validation errors that I believe should be correct. For example, the first is using `@component` [which should be valid](https://pretextbook.org/doc/guide/html/publisher-versions.html#subsection-149):
<img width="1152" alt="2023-07-04_13-58-04" src="https://github.com/oscarlevin/pretext-tools/assets/84139/722afbee-6126-48cf-b3ad-10d1970276f8">

The second is using `slate` element, which although I don't see in the manual any more, I hope it's still available:
<img width="914" alt="2023-07-04_14-05-12" src="https://github.com/oscarlevin/pretext-tools/assets/84139/e66502ae-5b4b-4932-aa3c-0662e7a2c621">

The rest of the warnings are reasonable things I should fix this summer.  If these are valid, is there a mechanism to ignore certain validation warnings? 

Thanks!

**Comment by angelozerr** [comment]
The validation is done with vscode-xml by using a rng schema I think.

It is not possible to ignore some errors. The proper fix is to fix the rng schema

**Comment by jmhammond** [comment]
Thanks! I'll look into that

**Comment by oscarlevin** [comment]
@jmhammond, the official schema is lagging behind a bit.  If you search vs code settings for pretext, you should see an option to use the experimental or development schema.  That will reduce the number of errors you see.

If you still see errors that you think shouldn't be, do let me know and I'll try to update the experimental schema with them.

**Comment by angelozerr** [comment]
Please note that vscode-xml provides an easy mean to open schema from xml and  edit it. If you save the schema, xml validation will be retrigered.

To open the schema and go where the validation rule is declared as xml, you open contextual menu from the xml node and clixk on go to type definition
