### ISSUE TITLE
Change `quick build` to `build [FOO]` where FOO is default/latest target

### ISSUE THREAD

**Issue by StevenClontz** [oscarlevin/pretext-tools#48]

**Comment by oscarlevin** [comment]
Agree.  And what if it changed to `rebuild latest target` after one has been built?

**Comment by StevenClontz** [comment]
I like it.

**Comment by StevenClontz** [comment]
(I may be using pretext-tools for a book this morning.)

Another thing to consider that's somewhat related: I kind of prefer keeping the list of targets in the order they appear in project.ptx rather than moving the most recent one to the top. If the most recent target was available at the root menu for building, this would offer the best of both perspectives perhaps.

**Comment by oscarlevin** [comment]
Of course!  No reason not to name the target...

And right, with this change, the other convenience isn't needed.
