### ISSUE TITLE
Add syntax highlighting for unsupported tags

### ISSUE THREAD

**Issue by oscarlevin** [oscarlevin/pretext-tools#5]
While it would be a long list, it wouldn't be too difficult to highlight any tag that is not a supported pretext tag.  I don't know what this would do for people who work on xml and pretext and have pretext-tools installed.

**Comment by angelozerr** [comment]
I have the impression that you are speaking about validation, vscode-xml supports that:

![image](https://user-images.githubusercontent.com/1932211/210138455-5cf90c4b-d374-45be-a78a-544129a2f12b.png)

**Comment by oscarlevin** [comment]
Yes!  This is now implemented via the support of vscode-xml
