### ISSUE TITLE
Incorrect syntax error highlighting with a compilable book.

### ISSUE THREAD

**Issue by Aljumaily** [oscarlevin/pretext-tools#87]
I have been using PreTeXt for several months now and I always get errors highlighted in VS Code (Version: 1.91.0), even if the syntax is proper. I know the syntax is correct because there are not issues when building the book using `pretext build web`.

For example, I have the latest version of the extension installed (v0.19.0) and have created a new book. The `pretext` tag in `main.ptx` is highlighted as the following error:
```
docinfo.ptx(8, 4): element "document-id" not allowed anywhere; expected the element end-tag or element "asymptote-preamble", "author-biographies", "brandlogo", "cross-references", "feedback", "images", "initialism", "latex-image-preamble", "macros", "math-package", "numbering" or "rename"
docinfo.ptx(10, 4): element "blurb" not allowed anywhere; expected the element end-tag or element "asymptote-preamble", "author-biographies", "brandlogo", "cross-references", "feedback", "images", "initialism", "latex-image-preamble", "macros", "math-package", "numbering" or "rename"
There is '1' error in 'frontmatter.ptx'.xml
frontmatter.ptx(21, 53): text not allowed here; expected the element end-tag
```

The goes to the `document-id` and `blurb` tags in `docinfo.ptx`. Also, adding the `interactive` tag gets flagged as  an error. I am using my personal machine to code and build the book. It is MacBook Pro M2 chip with Sonoma 14.5 as the operating system. Any suggestions would be helpful.

<img width="579" alt="main-error" src="https://github.com/oscarlevin/pretext-tools/assets/44656681/252e678f-4ac9-4097-aa8e-25c122837d40">
<img width="587" alt="docinfo-error" src="https://github.com/oscarlevin/pretext-tools/assets/44656681/84e878d9-8b6f-46d4-9d7f-a1ee86e7827b">

Thank you in advance!

**Comment by mitchkeller** [comment]
These things are not yet in the official PreTeXt schema, which is why they're being flagged. If you go to your VS Code settings and search for schema, there is a setting called Pretext-tools > Schema: Version. Change from Stable to Experimental and these validation issues should go away.

**Comment by Aljumaily** [comment]
@mitchkeller Thank you for the kind response! It worked 😃!
